### ISSUE TITLE
Overlapping text prob

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#115]
hs 6147

<img width="530" alt="1-last panel of text" src="https://user-images.githubusercontent.com/228608/159294608-029b3ba5-6418-412d-96bf-61acb0d8469e.png">

**Comment by ClocQ** [comment]
In 2022.s.SARGASSO at Japanese environment, This Issue is also occurred.
Occurred once when opening the token after completion of the "study" token. It does not seem to occur very often.
A video of the occurrence is attached.

https://user-images.githubusercontent.com/85084193/165458301-08539bf3-75d0-4a9b-9c73-276fbc6991fc.mp4

It also appears that the issue may be clear by the operation of moving the text history. I also attach a video here.

https://user-images.githubusercontent.com/85084193/165458557-321aac3c-b110-4f74-b650-0a321de005d6.mp4

**Comment by ClocQ** [comment]
I am pleased to tell you that we have found that it can be generated intentionally to some extent.

The procedure is as follows
(1) Right-click on one of the cards ("An Affiction" in the video) without "verb" open, and open "verb".
(2) Immediately after opening the verb, press the [Esc] key to close the verb.
(3) Right-click again on the card used in (1) to open the verb.

The [Esc] key in (2) seems to be more likely to occur if you press it about the moment you see the word of "verb". I think the rate of occurrence is about 50%.
The operation was performed in v2022.5.y.1 YERMA.

A video is attached for your reference.

https://user-images.githubusercontent.com/85084193/168824058-4b9c25f7-98e0-41d5-aee3-488f99e14f7e.mp4

.

**Comment by Chelnoque** [comment]
![изображение](https://user-images.githubusercontent.com/10981532/182880680-903ff1f5-1cea-4a30-b4aa-6cb0f411b466.png)

I waited for this.
