### ISSUE TITLE
Fiddly restart button

### ISSUE THREAD

**Issue by Genroa** [weatherfactory/cultistsimulator-visible#156]
Hello, a small visual/UX thing. When we click on the restart button (while in game), its label changes. This is normal, a two step process to confirm that you really want to restart. But in its second stage, the button's valid hover/click zone becomes really tiny (somewhere on the left maybe?) that you need to move your mouse a bit all around to try to find it and see it react visually. Most of the area of the button itself doesn't react at all.

**Comment by Chelnoque** [comment]
The impression of incorrect behaviour is caused by the delay before the button becomes interactable again (this is confirmed). The delay is 2 seconds (some warmups are shorter ;) 
In my impression, it's *too* long indeed and must be 0.75s tops, but I can kinda see why you might want to keep it this long. @alexiskennedy how do I proceed?

**Comment by alexiskennedy** [comment]
2 seconds was a totally arbitrary number - 0.75 sounds fine!
