### ISSUE TITLE
Cards are insistently homing into the slots

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#160]
It appears that cards can somehow decide that their home sphere is inside a threshold?

Reported here: https://steamcommunity.com/app/718670/discussions/0

And addendum:
https://user-images.githubusercontent.com/10981532/173498382-826dd7a7-213b-4b95-b58f-9d5b98f76fbe.mp4

**Comment by Chelnoque** [comment]
Confirmed, dragging a token from one Threshold to another makes the former to become a home for that token. 
Simple enough to forbid Thresholds becoming homes altogether, but are we sure that at some point there won't need to be for Threshold!Home? Probably too early to care.

**Comment by alexiskennedy** [comment]
>Probably too early to care.

It's never too early to care, it's sometimes too early to care enough...

HomingAngel is due a refactor to fix another longstanding irritation: that cards don't remember home locations through reloads. Angels aren't saved (by design). A HomeLocation property on a token can and should be. (In the old code, tokens stored a home location vector on the tabletop - this was another constant null reference trap) I started making this change the other week but ran into edge cases and had to revert.

Once this change is made, we can have sphere classes set home location on the token, or not, so we don't need an ugly 'if spherecategory!=threshold || oops another new category)' catch. But for now an if + comment will do fine!
