### ISSUE TITLE
Looping Enemy Long

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#175]
hs6754:

"This bug occurs in a saved game that is a week long. I've also tried to restart my game to replicate it - but game boots me back to an Aspirant start, instead of an advanced one.

Enemy long is in a loop with two actions - "Preparing an Action", then "Report from our spy" and then it goes back to "Preparing an Action"
[hs_6754.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/9111197/hs_6754.zip)

This is the only report, it's 6.c.2, and the absence of a restart file suggests it was a save that had been converted from the old format - so there may be shenanigans from that. So it's low priority. But I'd like to work out what happened if possible.

**Comment by Chelnoque** [comment]
Ok! Time to finally conclude this one.
The imminent problem was that the Long lacked an Intent - one of stratedy.* elements that determine the type of action they'll perform once preparations are over. Thus they were stuck in an endless loop of indecisiveness. Really makes you think, huh?

Normally, intent card is drawn before the adversary enters the preparation loop, and there's no failsafe. 

Not clear how exactly it can be missing. Two possibilities:
a) it wasn't there in the first place due to some kind of legacy version bug;
b) default card was drawn from a strategy deck. The card had wrong ID (until recent importer update), and will lead to this exact behaviour both on up-to-date and petromneme saves. This draw shouldn't be possible (decks reset on exhaustion, so default card shouldn't be ever touched), but the coincidence here is suspicious.

Inspecting petromneme didn't show that it could somehow just lose a card from a verb if there's everything alright with it. So root of this is not clear and probably ever won't. 
Added a failsafe just in case and wrong ID was fixed even earlier.
