### ISSUE TITLE
[MEHEN] Slow frame rate / forbidding redraw loop?

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#178]
I've had a couple of reports of slow frame rates and crashes that might be associated with some looping nonsense in marking unique elements as manifested.

eg this from a player.log:

>>>>>>> Unique element manifested: geminiadfucine
>>>>>>>> Forbidding redraw of geminiadfucine from deck.explorevaultcontinent4_success
>>>>>>>> Forbidding redraw of geminiadfucine from vaultrewardsc
>>>>>>>> Unique element manifested: geminiadfucine
>>>>>>>> Forbidding redraw of geminiadfucine from deck.explorevaultcontinent4_success
>>>>>>>> Forbidding redraw of geminiadfucine from vaultrewardsc
>>>>>>>> Unique element manifested: geminiadfucine
>>>>>>>> Forbidding redraw of geminiadfucine from deck.explorevaultcontinent4_success
>>>>>>>> Forbidding redraw of geminiadfucine from vaultrewardsc
>>>>>>>> Unique element manifested: geminiadfucine
>>>>>>>> Forbidding redraw of geminiadfucine from deck.explorevaultcontinent4_success
>>>>>>>> Forbidding redraw of geminiadfucine from vaultrewardsc

I initially thought it was a drivers issue because it was so rare, but this seems to be a theme.

[Player.log](https://github.com/weatherfactory/cultistsimulator-visible/files/9113595/Player.log)

[hs6552]
[hs6645]

**Comment by alexiskennedy** [comment]
[Crash_2022-06-26_210809933.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/9113655/Crash_2022-06-26_210809933.zip)

Here's a player.log with an accompanying crash.dmp showing a stack overflow.

**Comment by Chelnoque** [comment]
Come to think of it, this is very likely the same thing as #179 

The code that registered uniqueness was a bit messy in the first place - maybe putting it in order made things better. But there were no apparent suspects for this exact problem. 

The closest thing I can think of is that putting a card in the forbidden pile caused another uniqueness check, but that reasonably shouldn't happen.

Put a pin on this for now.

**Comment by alexiskennedy** [comment]
One of the users who reported this issue came back this morning and said that late-game performance seems much improved in FRAGRANTOLIVE. I'm going to take this down a pri notch.

**Comment by alexiskennedy** [comment]
I'm still getting people reporting this, including one who says it is still an issue in FRAGRANTOLIVE (2022.7.f.3).

One does say "Seems that it happens most often just after card collection" so it still seems likely it's the same issue as #179.

I'm going to take a look at it now - I may add a guard clause to repeated uniqueness checks on the same ID.

[Playerlogs.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/9218553/Playerlogs.zip)
)

**Comment by alexiskennedy** [comment]
Naming this crash MEHEN

**Comment by Chelnoque** [comment]
Worth noting:

The log in the second comment looks like a proper stack overflow - the game got stuck endlessly manifesting Tristan on the table. Let's call this MEHEN 1. 
(no idea how this could happen, honestly. maybe not a loop, but the homing angel problem, so tristan indeed was just moving between the spheres constantly? or, as I suggested earlier, maybe forbidden pile caused anyther forbidding, which caused another forbidding, which caused another forbidding?)

Most other logs indicate no loop, just a normal uniqueness behaviour, but cause a crash. I still believe that the game just overworks itself, manifesting/forbidding/handling events for 7-10 cards is a lot of work - forbidding from just 2 decks means we're effectively handling thrice as many tokens. I've reduced the strain for uniqueness checks, but it's still far from being the most lightweight thing in existence, and there are other pretty performance-consuming things at play. 
Let's call this MEHEN 2. 

Limiting uniqueness checks per element ID shouln't fix MEHEN 1 entirely - because *if* there's a rare case when check can cause a loop, it still be there. But will reduce chance of it appearing, less checks = lesser chance that something goes wrong.
(on the other hand, maybe MEHEN 1 is already fixed)

How limiting uniqueness checks will affect MEHEN 2 depends on the implementation. Most overhead here comes from the freshly-created unique elements anyway. Consequently, check will happen anyway - these elements never manifested before, uniqueness checks/forbiddings *should* happen. But that means that in such cases limiting can create *more* overhead, not less, because, on top of the previous uniqueness check code, there will be another check whether an uniqueness check already happened, and the code that prevents uniqueness check to happen in future.

But if we remove forbidding piles from the equation entirely - say, will be keeping forbidden uniqueness ids in the Character instead, or in a deck DrawPile, but as strings, not as tokens,  - that'll optimize the check code in the first place, and will reduce the strain even further.
(that's why I was proposing it in the first place!)

**Comment by alexiskennedy** [comment]
My suspicion is MEHEN 2 is unrelated to uniqueness. I could be wrong! Either way I've christened it KHAINO for clarity.

I'd like to leave forbidden piles as tokens for a while longer. If there are perf issues, let's use the perf analyser to track down the hot spots and address it. The other thing is that if we need to check properties on forbidden-pile contents, we may need to spin up a token or at least an element anyway - I remember now that this is one of the other reasons I went this way, when they were originally just key:pair values.

*However*, it seems obvious in hindsight that we don't need a forbidden pile for every single deck! We just need one forbidden pile for the whole table. There is no case where Ezeem should be in acquaintances but not in summonableacquaintances. So I like the idea of that refactor. It might or might not help with perf, but it certainly makes content debugging easier.

Finally, I notice the crash log with the stackoverflow is from DAHLIA anyway. So I'm taking it back down to 5. I've added a small performance tweak and some logging, though.

**Comment by Chelnoque** [comment]
So, MEHEN 1, or just MEHEN. 
The exact reason was that sometimes cards would make their home at EnRoute. This happened when you dragged a card and it got pulled by a greedy slot - need to be extra careful with what can be home and what can not!

Fixed in HELLEBORE.
