### ISSUE TITLE
Cards spam hover sound when dragged

### ISSUE THREAD

**Issue by AliceTheCyndaquil** [weatherfactory/cultistsimulator-visible#184]
(couldn't see any other reports on this, delete if I'm wrong)

I wasn't able to narrow down the exact action that caused this, as it usually just happens. It seems to have something to do with cards auto-stacking. persists after saving and quitting. 
https://user-images.githubusercontent.com/109806990/180469533-a46ddbfc-c283-431b-92d4-cbf21eb9102c.mp4

**Comment by Chelnoque** [comment]
Distilled save:
[save.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/9259137/save.zip)

Only Work and Health tokens on the table. Will look later.

**Comment by alexiskennedy** [comment]
pri 5?? For a first-time report?? Sorry, I must have been having an anxious day.

**Comment by Chelnoque** [comment]
What do you know, this one *too* turned out to be much deeper than it looks - and much more common too!

Apparently, this happens (happened), when there is a card in a verb (say, Health while you're working), *and* you're dragging a card of the same entity (say, another Health). The game tries to highlight all possible interactions for it and - what do you know! - elements inside of verb storage are perfectly eligible, because why not? They have the same id. Thank god there's no interface to actually do that. 
So, the sound was just a surface symptom - the way how StoredManifestations are react to being highlighted. Up to a certain point that was non-issue as elements in storages couldn't possibly merge anyway. This was always an issue since they could. 

A concept of "reachability" between spheres is introduced. Contents of a sphere won't interact with contents of another sphere is it can't be "reached". Rules of reachability is quite simple (now):
- If Sphere is Exterior, it can be reached from anywhere. Thus tokens, that are immediately available for the player [to interact with], can interact with everything.
- If Sphere is not Exterior, it *can't* be reached from anywhere but itself. Thus tokens, that *aren't* available to the player, *won't* interact with anything else (except other tokens in the same sphere).

This is sufficient for CS. BoH may or may not require some more in-depth tinkering.

**Comment by alexiskennedy** [comment]
>This is sufficient for CS. BoH may or may not require some more in-depth tinkering.

I think this is good for BH too, actually. Earlier prototypes had a concept of 'range', but now everything is (broadly) accessible to the player or inaccessible to the player.
