### ISSUE TITLE
Enroute is visible in Otherworld

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#189]
https://www.reddit.com/r/weatherfactory/comments/wcqy5x/there_are_new_areas_in_the_mansus_since_the_new/
(note the itty-bitty season of despair between the cards)
Also mentioned in #173.

The issue is in the rendering layer order, switching it will fix this, BUT maybe for BoH it will be required that Enroute *must* be visible in Otherworld? That will require two different enroutes, with two different rendering layers.

**Comment by alexiskennedy** [comment]
BoH does in fact have two different EnRoutes. And I think that resolving this bug in CS would also need two different EnRoutes... because when you're dragging the Mansus cards around, they gots to appear somewhere, right?

Or a different solution where all non-Mansus cards are temporarily hidden when the Mansus opens, but I think that will almost certainly be more work and a more significant risk of bugs.

**Comment by Chelnoque** [comment]
Oh, right - but MansusEnroute isn't a separate rendering layer, it renders on the Numa and is above because it's below in the hierarchy. So there's no problem in fixing that, as for now.
