### ISSUE TITLE
Disable All Mods on Crash?

### ISSUE THREAD

**Issue by Chelnoque** [weatherfactory/cultistsimulator-visible#207]
If a mod causes a crash, user is stuck with no legit means to disable it - only to edit mods.txt which is, obviously, sub-optimal. Probably worth adding "Disable All Mods" button on the cat screen.

**Comment by alexiskennedy** [comment]
Better yet, let's change the line in Mods | Description from

"You have mods enabled! First, please disable all mods to see if that fixes your problem.
If you send a bug report, please specify any mods you have installed.
IF YOU DON'T, THE CAT WILL BE EXTREMELY SAD."

"At least one mod was enabled - we've disabled all mods to put the game in safe mode.
If you send a bug report, please specify any mods you have installed.
IF YOU DON'T, THE CAT WILL BE EXTREMELY SAD."

**Comment by alexiskennedy** [comment]
and then obviously add a line of code to disable all mods, which I would do by overwriting mods.txt rather than going through ModManager.

Why? (1) If something is breaking in the modding system, we don't want to get into a loop redirecting to the error page (2) if we put a button on the error page and say 'click this button', ALMOST NO-ONE FOLLOWS INSTRUCTIONS. You wouldn't believe the number of error logs I get which clearly show a mod running but they don't tell me they had mods.

**Comment by alexiskennedy** [comment]
'what if someone has 20 mods enabled and the crash disables them all and it's a pain to re-enable

good point, imaginary Roman. Let's copy to mods.txt.bak. Other suggestions welcome

**Comment by Chelnoque** [comment]
I would actually say "but imagine how annoying it will be for modders to need to re-enable each time they made a typo in JSON". Anyways, destination is the same!

Makes sense that nobody will press the button. Maybe the opposite then - when the game loaded successfully, a button to re-enable all previous mods from mods.txt.bak?

**Comment by alexiskennedy** [comment]
This button would be in the mod manager? That sounds good.
==
Before I sign off on it, though, one alternative. Is there any modder value for a dev=1 config.ini switch for modders? 

There are a number of places where Application.IsEditor forces different behaviour - most notably, it shows the error details on the tabletop console log, rather than the error screen.

So if dev=0, a user with broken mods sees the cat screen and all mods are disabled (and mod.txt backed up, which is useful to see which mods *were* enabled* after the fact). If dev=1, a modder with sees the tabletop screen with an error log saying 'wrong json bro'. (And whatever else is useful to add as behaviour - this could replace the knock=1 switch for cheevo cheat enable)

**Comment by Chelnoque** [comment]
It's a good idea, but I think it's worth implementing both. Most people won't be using dev mode, so it's doesn't really replace "restore last mod setup" button. 

Left the config value as "knock" for now (unless there are objections to that).
While implementing, got a suspicioun that not giving a crash once an error occurs won't be helpful outside of the Editor - once a single error occurs, it often starts to spam, so it'll actually be harder to find a usefull message. 
We'll see how it fares.
