### ISSUE TITLE
UIHAND SPHERES ('TRAYS')

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#231]
see row 5 in spreadie

**Comment by alexiskennedy** [comment]
Setting to pri 5 until all crash issues confirmed fixed

**Comment by Chelnoque** [comment]
Done, with three various implementations to choose from:

1) As initial scene setup suggested - three distinct trays, each with its own buttons, each can be dragged/sorted separately
2) "TraysAsOne" - all trays are dragged/sorted together
3) "TraysHorizontalDrag" - mostly just as proof-of-concept. In more elaborate implementation, it can
  3.1) loop horizontally
  3.2) allow to pull out only the "central" tray, so others don't obscure other parts of the interface; although with non-transparent trays sprite this may be a non-problem

We can go with any amount of blend between these three. 
Currently, there can be little individual problems in each implementation (as in "cards overlap buttons"), I'll tidy everything up as soon as we determine the course.


Thoughts, ideas & suggestions:

- I'm moderately wary of the idea that some cards can went and decay off-screen. CultSim had this unpleasant tension "haven't I forgot about something important with a timer" going on, and I feel like, while there's less cards, having them explicitly out of your sight doubles down on that feeling and encourages permanent compulsive drag-peeking into the trays.

- Sorting trays (with a button) can have more thoughtful algorithm of prioritisation. In re: above, as a test, I made it so cards with a lifetime are displayed earlier, but there's more to think of: i.e. deprioritise cards with "fatigued"/"exhausted", husks and such.

- Cards should probably stack automatically on entering, or decaying into something stackable. Partly so that each element is more informative - ie this is *overall* Phost you have, this is *all* money you have, given you don't have a dedicated status bar anymore. But mostly because otherwise player will be able to fill every empty space with a penny and giggle at us as we fail to find an appropriate space for an incoming card. Maybe commutes should happen automatically too.

- Speaking of, will there even be enough space? If each Wisdom has 10+ skills, then, pessimistically, skill tray is roughly 3-5 times shorter than it should be. 

- Maybe there's a merit in making trays even more auto-sorted by the game. For ex., maybe elements that are about to expire should be placed above *automatically*; maybe similar elements - like money, like z/x versions of abilities - should be grouped *automatically*. Maybe there should be a single row of a dedicated hotbar, wholly player-controlled, and a single auto-sorted tray, that's visible, say, on 1/4 of a card by default? This way it can still draw player's attention to something that can be important (like "new cards first", "expiring cards first", whatnot) without being too intrusive.

- Don't think there's a point to have a dedicated "sort" button for each tray separately. It occupies precious space, and I don't think "being able to sort one tray but not the others" is a valuable tradeoff here.

- I think that ability to drag the tray partway up should stay in any case - it allows the player to control how much of the tray they want to see at any given moment. 

- I think that ability to drag each tray separately should stay (that is, if we're going with the idea that there should be several distinct trays instead of one tray with more elaborate sorting algorithm). Partly because it'll obscure less screen space, but mostly because it feels like a toy with more moving parts, therefore it's more tactilely pleasant to interact with.

**Comment by alexiskennedy** [comment]
Thanks! Added feedback points and change requests here: https://docs.google.com/document/d/12gvrbl8pQLiSUJI0f7bxo4Kc2WOpvTdZjTVZhmVbgVk/edit
