### ISSUE TITLE
User claims Extends doesn't work??

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#254]
No idea if there's anything in this? I suspect user error but he's been very conscientious.

(hs 7653)

===
"Dear Kennedy,

I recently found "extends" in mods have no effects on modifying the recipes (or elements, etc.) of the original game. So I made some mods to test and verify this. (The testmods, Method and Result see attachment.)

To make a conclusion: in fact, extends doesn't have any effect. To modify those, one can rewrite those part he wants to change, with or without "extend" is both OK. Also, it seems that there is no method to modify the "description","label" of endings (and "description","label","startdescription" of legacies) of the original game. I guess that's because the code to display those texts is different from texts in recipes, elements.

It is interesting that the results of test 0&0.1 and test2&2.1 are different, though they changed almost the same thing.

Thank you.(I don't know how to start or enclose a mail sorry _(:з」∠)_ )"

[Attachments.zip](https://github.com/weatherfactory/cultistsimulator-visible/files/10901145/Attachments.zip)

**Comment by Chelnoque** [comment]
"Extends" doesn't work as a way of modifying vanilla properties - it was used like that in the most primordial form of Lyrositor's framework, but changed since the Workshop update. Now it's just a way to inherit properties. So the user probably just needs pointing towards the newer guides. Although there already was a person in #modding with a similar question, so I suspect this is resolved already.

The part about Endings and Legacies not being editable is puzzling, but I'll check. Also will check if $extends are working in general, just in case.

**Comment by alexiskennedy** [comment]
Please do check but for crikey 's sake man it's after midnight there!! No urgency.

BTW I spent today cleaning up my BH task list - some more stuff for you coming soon.

**Comment by Chelnoque** [comment]
As expected, extends and editing Legacies/Endings work - probably a user error.

Looking forward to BoH tasks!
