### ISSUE TITLE
Ghost perpendicular projection is a problem

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#29]
[Genroa on Twitter]

Also the use of a line trace perpendicular to the table to try to find the position for the ghost makes placing anything that isn't directly in the center of the screen a chore, and makes entire areas of the board unusable unless you move the camera, event Hough they are visible.

**Comment by alexiskennedy** [comment]
(I'll take a look)

**Comment by Genroa** [comment]
Hello,

Here is the link to the document that never reached you: https://docs.google.com/document/d/1IeMWZ-rI2vCea2OL4g7mLkDwSVr1X-XVCMwQBbNX6GA/edit?usp=sharing

Reading it again, even with the pictures, I fear it wasn't very clear. Also there are pictures everywhere so it can be hard to read. (It also talks about the snappy camera and the missing edge drifting.)

I will try to provide a clearer "supposition" of what's happening, and a shorter one too:
- the final ghost's position seems to be computed perpendicular to the table, not relative to the camera view. This makes the final position very counter-intuitive when the card is away from the center of the view ("away" can probably vary a lot from screen to screen here I suppose, on a 1920x1080 the problem becomes very visible very quickly)
- the final ghost's computed position may have a rounding error in the grid somehow? cf. document pics, slightly moving a card nearly perfectly overlapping its ghost can make the ghost jump to the next position after only a few pixels instead of more than half the card over it
- the cards may be higher than before when you drag them, reinforcing the effect?

This behaviour often leads to situations where you feel like "it should drop where it is on the screen", but the ghost makes it clear it will absolutely not fall there, even without obstacles around (cf. the screenshots in the document)

I will detail the other points in the correct issues.

**Comment by alexiskennedy** [comment]
more from [Genroa](https://github.com/Genroa)

 https://www.youtube.com/watch?v=Brq3qRv5bMA

visual example of a potential bug with the way the card's new position is handled. Contrary to what my confusing video explanation says, its biased towards the center, not only in one direction on each axis. So this could still be a trick of the perspective, because the camera I used was perfectly facing downwards but wasn't othographic (I would have needed to rewrite the entire zooming behaviour and I really didn't want to do that just for a test). But the bias seems...way too strong and happens relative to the center of the table it seems, and not relative to the camera's current position?

**Comment by alexiskennedy** [comment]
On the fix list now I understand what's happening here. (correct for ghost perpendicular placement)

**Comment by alexiskennedy** [comment]
Implemented in WUTHERING. For the record [Genroa](https://github.com/Genroa) you were right about this (except in the technical implementation, it's not actually a ray trace). It took me a long time to realise how significant it was because it never bothered me. The perils of subjectivity.
