### ISSUE TITLE
Card's final position (ghost) computation error?

### ISSUE THREAD

**Issue by Genroa** [weatherfactory/cultistsimulator-visible#31]
(as with other GitHub issues related to the camera and cards, pictures of the behaviour can be found at this link: https://docs.google.com/document/d/1IeMWZ-rI2vCea2OL4g7mLkDwSVr1X-XVCMwQBbNX6GA/edit )

Happens on: beta/main

**Behaviour:**
- the final ghost's computed position may have a rounding error in the grid somehow? cf. document pics, "Factor 2") Slightly moving a card nearly perfectly overlapping its ghost can make the ghost jump to the next position after only a few pixels instead of more than half the card over it
- obstacles can lead to very wrong final positions. An easy way to reproduce it is to drag a card around one of the dropzones, around a verb, or a set of cards on the table, or to make a cross with an empty space in the middle.
- cards can be dropped in positions not aligned with the grid

**Comment by alexiskennedy** [comment]
Cheers! I just looked back through my emails and found that our mutual friend *did* send me that link previously. But he sent me four emails with six links, and I missed the sixth link when I caught up on them after a month away. If I'd started using a public issue tracker three months earlier, things would probably have gone better. Lesson learnt :)

**Comment by Genroa** [comment]
No, I shouldn't have acted that way. I'm really sorry about that, you really didn't need that after the entire response on Steam.

Also, update: I jumped back from classic ui to the main, and I can confirm the 1/4th grid makes things a bit better!
The issue is still there though, so here is a gif:
![card_placement_bug](https://user-images.githubusercontent.com/4357574/156832082-efbc9708-7f18-4999-89fc-b2d029e2bd5f.gif)
(especially near the end, you can see how vertically moving it slightly leads to a totally different selected cell on the grid, even though the card visually very much still overlaps the original position)

**Comment by alexiskennedy** [comment]
At least two things are happening here. The first I didn't know about, and have fixed; the second I didn't realise the implications of, and will amend.

(1) When dragged, the rotation of the card is subtly changed with a bit of Perlin noise (another of my original UI dev's grace notes). Unfortunately, the ghost's location was also affected by the noise, so it behaved a bit more predictably. I've decoupled the two and this will clean things up a bit.

(2) the placement algo is pretty naive: it just looks in a series of concentric rings around a blocked grid-snapped  ideal placement point, starting with the least-blocked angle. This worked okay when cards would shuffle each other aside, because if it couldn't find a good location, it would make one by shuffling others aside. I never liked that behaviour, though, and I don't want to go back to it.

So in your second gif, the card can't find a grid-snapped location in the first or second ring, and it looks farther afield. This makes sense if you know what it's doing, which is why it seemed fine to me, but of course 95% of people don't think like that!

If the original placement point is not grid-snapped first, that may improve it. If I change the gridsnap scale from 1-1/4 to 1/2-1/8, that may improve it further, but some people may like 1-card snap. I'll sleep on it. Thoughts from you or others are welcome.

>No, I shouldn't have acted that way. I'm really sorry about that, you really didn't need that after the entire storm on Steam.

The internet is a machine for making people crazy. Thanks for being mature here: we're cool.

**Comment by alexiskennedy** [comment]
The idea I should have thought of in November. Why do I need the exact same algo for placement by engine and placement by player? They can put it anywhere on the table that aligns with the grid, and the grid is now by default 1/8 card size.

```
            //If the player is deciding where to place the token, they have NEAR ULTIMATE POWER
            if(placingToken.CurrentlyBeingDragged())
                return LegalPositionCheckResult.Legal();
```

**Comment by alexiskennedy** [comment]
Mod looks interesting btw. gl!
