### ISSUE TITLE
Tofu and missing UI label in English with Turkish settings

### ISSUE THREAD

**Issue by alexiskennedy** [weatherfactory/cultistsimulator-visible#86]
hs 5960

inclined to make it pri 8 but it might have other effects.

**Comment by alexiskennedy** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2777301927
https://steamcommunity.com/sharedfiles/filedetails/?id=2777301956

**Comment by Chelnoque** [comment]
The game currently is 100% capable of displaying Turkish symbols:
![Безымянный](https://user-images.githubusercontent.com/10981532/177561574-ef1bd371-6863-46db-8674-6b30e100eade.png)

Screenshots are from March and you've changed font setting since then at least once. The research gave me an idea of another safenet against MISSING_UI and possible other problems of the same kind though.
